

#ifndef EJERCICIOSPROGRAMACIONESTRUCTURADA_ESTUDIANTE_H
#define EJERCICIOSPROGRAMACIONESTRUCTURADA_ESTUDIANTE_H


struct Estudiante {
    char nombre [50];
    int edad;
    float promedio;
};


#endif //EJERCICIOSPROGRAMACIONESTRUCTURADA_ESTUDIANTE_H
